snyk/parlay

- internal/commands/ecosystems/enrich.go
- internal/commands/snyk/enrich.go
- internal/utils/input.go
- internal/utils/input_test.go
Getting feet wet. This refactors the filename/stdin behaviour in `enrich` commands and moves the logic to a common `utils` package, with tests for test coverage.
> refactor: move reading of input to utils package

- README.md
- internal/commands/default.go
- internal/commands/scorecard/enrich.go
- internal/commands/scorecard/root.go
- lib/scorecard/enrich.go
- lib/scorecard/enrich_test.go
Currently this just adds an external reference when it finds the project has available scorecard data. Looking into whether or how best to add the score to the BOM as well.
> feat: Add enrichment using OpenSSF Scorecard data.

- internal/utils/spdx.go
- lib/scorecard/enrich.go
- lib/scorecard/enrich_cyclonedx.go
- lib/scorecard/enrich_spdx.go
- lib/scorecard/enrich_test.go
- lib/snyk/enrich_spdx.go
This adds SPDX support to the `parlay scorecard enrich` command. Logic is pretty much the same as it is for CycloneDX, just using a few early returns instead of nested `if`s.
I tried to see if we could improve perf by making a HEAD request to the Scorecard API; which they unfortunately don’t support…
```bash
$ parlay scorecard enrich testing/sbom.spdx-2.3.json | jq ".packages[1]"
{
"name": "debug",
"SPDXID": "SPDXRef-2-debug-1.0.5",
"versionInfo": "1.0.5",
"downloadLocation": "NOASSERTION",
"filesAnalyzed": true,
"copyrightText": "NOASSERTION",
"externalRefs": [
{
"referenceCategory": "PACKAGE-MANAGER",
"referenceType": "purl",
"referenceLocator": "pkg:npm/debug@1.0.5"
},
{
"referenceCategory": "OTHER",
"referenceType": "openssfscorecard",
"referenceLocator": …
```
> feat: add SPDX support to scorecard

- lib/ecosystems/enrich.go
- lib/ecosystems/enrich_cyclonedx.go
- lib/ecosystems/enrich_cyclonedx_test.go
- lib/ecosystems/enrich_spdx.go
- lib/ecosystems/enrich_spdx_test.go
This adds SPDX support to the `ecosystems enrich` command.
```bash
$ parlay ecosystems enrich testing/sbom.spdx-2.3.json | jq ".packages[1]"
{
"name": "debug",
"SPDXID": "SPDXRef-2-debug-1.0.5",
"versionInfo": "1.0.5",
"downloadLocation": "NOASSERTION",
"filesAnalyzed": true,
"homepage": "https://github.com/debug-js/debug",
"licenseConcluded": "MIT",
"copyrightText": "NOASSERTION",
"description": "Lightweight debugging utility for Node.js and the browser",
"externalRefs": [
{
"referenceCategory": "PACKAGE-MANAGER",
"referenceType": "purl",
"referenceLocator": "pkg:npm/debug@1.0.5"
}
]
}
```
> feat: add SPDX support to ecosystems enrich

- lib/snyk/enrich_cyclonedx.go
- lib/snyk/enrich_test.go
- lib/snyk/self_test.go
- lib/snyk/testdata/no_issues.json
- lib/snyk/testdata/numpy_issues.json
- lib/snyk/testdata/self.json
This is to improve the test coverage of `parlay snyk enrich`. This should enable us to refactor with more confidence.
It also fixes a small quirk where CycloneDX SBOMs with no detected vulnerabilities will still be extended with `{ ..., "vulnerabilities": null }`
> test: improve test coverage of snyk package

- CODE_OF_CONDUCT.md
This PR changes the email address for reporting code of conduct issues to the newly created oss-conduct-reports@snyk.io address.
> Update email address for reporting code of conduct issues

- go.mod
- go.sum
- lib/ecosystems/package.go
- lib/ecosystems/package_test.go
This adds support for purl types `docker` and `swift` when enriching via ecosyste.ms.
It also fixes an issue with the package name mapping logic, where the `maven` logic was applied to most purl types.
It also resolves `apk` purls to repository `alpine-edge`, since `alpine` on its own is not complete.
> feat: add ecosystems support for docker, swift

- README.md
The underlying API now supports golang purl types. Updating the docs.
> Add go to the Snyk docs

- .circleci/config.yml
- .pre-commit-config.yaml
- add gitleaks precommit
- add prodsec secrets scanning via circleci as github actions for same are not supported for public repos (see https://snyksec.atlassian.net/wiki/spaces/PRODSEC/pages/1563787412/Secrets+Scanning#3.4.2.-Using-ProdSec-Tools-in-a-GitHub-Action)
> chore: add secrets scanning

- internal/commands/snyk/enrich.go
- lib/snyk/enrich.go
- lib/snyk/enrich_cyclonedx.go
- lib/snyk/enrich_spdx.go
- lib/snyk/enrich_test.go
This passes the logger instance down to `snyk enrich` functions to add meaningful debug output.
Closes #47.
```bash
SNYK_TOKEN=asdf ./parlay snyk enrich testing/sbom.spdx-2.3.json
7:00AM ERR Failed to fetch vulnerabilities for package. error="Failed to get user info (401 Unauthorized)" purl=pkg:npm/package-file-basic@1.0.0
7:00AM ERR Failed to fetch vulnerabilities for package. error="Failed to get user info (401 Unauthorized)" purl=pkg:npm/minimatch@3.0.0
7:00AM ERR Failed to fetch vulnerabilities for package. error="Failed to get user info (401 Unauthorized)" purl=pkg:npm/debug@1.0.5
7:00AM ERR Failed to fetch vulnerabilities for package. error="Failed to get user info (401 Unauthorized)" purl=pkg:npm/ms@2.0.0
7:00AM ERR Failed to fetch vulnerabilities for package. error="Failed to get …
```
> fix: print debug output for issues during snyk enrich.

- internal/commands/snyk/packages.go
- lib/snyk/enrich_cyclonedx.go
- lib/snyk/enrich_spdx.go
- lib/snyk/package.go
- lib/snyk/self.go
- lib/snyk/self_test.go
This PR addresses two issues:
* #48: `getSnykOrg` did not return error if request to self endpoint was unsuccessful, resulting in a `nil` pointer UUID
* #46: package vulnerability lookup was making a request to the self endpoint for each package within an SBOM
> fix: user info

- lib/ecosystems/package.go
- lib/ecosystems/package_test.go
Remove initial url encoding for `npm` purls which broke ecosystem.ms requests for purls with namespaces
> fix: wrong encoding for npm package requests for ecosystem.ms

- acceptance.bats
- go.mod
- go.sum
- testing/sbom.cyclonedx-1.5.json
Update `cyclonedx-go` to `v0.8.0` to support parsing cyclonedx 1.5 SBOMs
> Add support for CycloneDX 1.5

- internal/utils/cdx.go
- internal/utils/cdx_test.go
- lib/ecosystems/enrich_cyclonedx.go
- lib/ecosystems/enrich_cyclonedx_test.go
- lib/scorecard/enrich_cyclonedx.go
- lib/scorecard/enrich_test.go
- lib/snyk/enrich_cyclonedx.go
- lib/snyk/enrich_test.go
- lib/snyk/testdata/pandas_issues.json
Implement deep component traversal when enriching CycloneDX SBOMs.
> fix: deep traversal of CycloneDX components

- .goreleaser.yml
- internal/commands/default.go
> Added version argument on the CLI

- go.mod
- go.sum
- lib/scorecard/enrich_spdx.go
- lib/scorecard/enrich_test.go
- lib/snyk/enrich_cyclonedx.go
- lib/snyk/enrich_spdx.go
- lib/snyk/enrich_test.go
- lib/snyk/package.go
Add external references to Snyk Vuln DB and Snyk Advisor to components when doing Snyk enriching.
> feat: snyk enrich external refs

- lib/snyk/package.go
This will result in clear debug logs when requests to the Package Issues API fail.
> fix: handle unsuccessful Snyk API responses

- lib/scorecard/enrich_cyclonedx.go
When doing a `parlay scorecard enrich` if the `repositoryUrl` field returned by `ecosyste.ms` is empty, the code will panic. 
In this change we add an additional check to prevent that behaviour.
> fix: empty ecosyste.ms repository url

- README.md
- lib/snyk/self.go
- snyk/issues/issues.go
- snyk/users/users.go
Currently `parlay` expects users to provide the Snyk API URL with the `/rest` suffix.
This change ensures that the snyk clients add this suffix automatically.
> feat: add "/rest" to snyk api url automatically

- lib/ecosystems/enrich_spdx.go
- lib/ecosystems/enrich_spdx_test.go
When enriching with ecosyste.ms, add the supplier of a package to an SPDX document.
Closes #76.
> feat: add supplier to SPDX documents

- .circleci/config.yml
- .github/workflows/ci.yml
- go.mod
- go.sum
- internal/commands/snyk/config.go
- internal/commands/snyk/enrich.go
- internal/commands/snyk/packages.go
- lib/snyk/config.go
- lib/snyk/enrich.go
- lib/snyk/enrich_cyclonedx.go
- lib/snyk/enrich_spdx.go
- lib/snyk/enrich_test.go
- lib/snyk/package.go
- lib/snyk/self.go
- lib/snyk/self_test.go
- lib/snyk/service.go
Replacing the dependency on `httpmock` with `httptest`. Making a start with the `snyk` command.
> test: replace httpmock

- go.mod
- go.sum
- lib/snyk/enrich_cyclonedx.go
- lib/snyk/enrich_spdx.go
- lib/snyk/package.go
- lib/snyk/package_test.go
- lib/snyk/service.go
When enriching a particularly large SBOM with Snyk vulnerabilities, the excessive amount of requests can trigger `429 Too Many Requests` responses.
This introduces a retry mechanism to account for such a case and honor the retry-after value coming from the Snyk API.
Closes #83.
> fix: handle Snyk API rate limit

- internal/utils/spdx.go
- internal/utils/spdx_test.go
- lib/ecosystems/enrich_cyclonedx.go
- lib/ecosystems/enrich_cyclonedx_test.go
- lib/ecosystems/enrich_spdx.go
- lib/ecosystems/enrich_spdx_test.go
- lib/ecosystems/package.go
When enriching with ecosyste.ms, fetch the license based on the package version.
Closes #87
> fix: return ecosyste.ms license based on package version

- lib/snyk/package.go
- lib/snyk/package_test.go
When calling the `Backoff` function of the `retryablehttp` client, the responses will be `nil` if an error occurs. This PR addresses this issue and also adds the `PassthroughErrorHandler` to the client in order to propagate more error details.
> fix: backoff function error handling

- go.mod
- go.sum
Upgrade to the latest release of CycloneDX library, fixing v1.6 schema issues.
Closes #100.
> fix: upgrade github.com/CycloneDX/cyclonedx-go to latest

- lib/snyk/enrich_cyclonedx.go
- lib/snyk/enrich_test.go
- lib/snyk/package.go
This change updates the Snyk API to the latest version for package information, which contains CVSSv4 information for some vulnerabilities. Note this change also fixes a big were the CVSS version was hardcoded to 3.1, and could have been either 3.0 and 3.1.
@mcombuechen this builds on top of your update to build the clients with the up to date specs, which suggests it works. If you land that, I can rebase that out of here if you like.
> Correct cvss version
